server:
  port: 5001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://39.105.193.114:3306/cat_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: 123456

